export const CName = {
	point: "game-point",
	tmpPoint: "tmp-point",
	activePoint: "active",
	gameContainer: "game-container",
	mapContainer: "game-map",
	menuContainer: "menu-container",
	gameInfoContainer: "game-info",
	infoContainer: "info-container",
	infoDesc: "info-desc",
	infoContent: "info-content",

	overContainer: "game-over",
	overTitle: "over-title",
	overDesc: "over-desc",
	overContent: "over-content",

	background: "game-bg",
	title: "title",
};
export const IDs = {
	map: "map",
	tmpPoint: "tmp",
	root: "root",
	view: "mainView",
	menu: "mainMenu",
	txbUserName: "txbUserName",
	menuHelloString: "lbHello",
	menuStartBtn: "btnStart",
	mapContainer: "mapContainer",
	nextBoxContainer: "nextBoxContainer",
	lbScore: "lbScore",
	lbUsername: "lbUsername",
	lbHello: "lbHello",
	nextBox: "nextBox",
	lbOverTimeLeft: "lbOverTime",
	lbOverHighScore: "lbHighScore",
	lbPlayerScore: "lbPlayerScore",
};
export const EContent = {
	title: "JS Tetris Game",
	start: "Start Game",
	lose: "You Lose!!",
	won: "Wow, You is not a Hunman",
	menuInput: "What Your Name, Hero?",
	descScore: " Score ",
	descNextBox: " Next Box ",
	hello: ["Hello, ", "Hi, ", "Thank You for Playing My Game, ", "Have a Nice Day, ", "Do You Like My Game, "],
	over: ["Thank You for Playing My Game, ", "Nice, Give Up Next Time, "],
	highScore: "High Score: ",
	playerScore: "Your Score: ",
};
export const LocalVar = {
	username: "userName",
	highScore: "highScore",
};
